name: wf1
on:
  schedule:
    - cron: "0 2 * * 1-5"
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 for testing
        run: echo "hello world!"
        
