name: wf1
on:
  schedule:
    - cron: "10 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 for testing
        run: echo "hello world!"
      - name: step 2
        run: |
            echo "step 2"
            pwd
            ls
        
