name: wf1
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 for testing
        run: echo "hello world!"
              sleep 10
      - run: |
            echo "step 2"
            pwd
            ls
            sleep 10
        
